CREATE TABLE `test_book` (
  `BOOK_ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `BOOK_NAME` varchar(32) NOT NULL,
  `BOOK_PRICE` varchar(32) NOT NULL,
  `CREATE_TIME` datetime DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_TIME` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`BOOK_ID`)
) ENGINE=InnoDB;

CREATE TABLE `test_user` (
  `USER_ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `USER_NAME` varchar(32) NOT NULL,
  `USER_AGE` varchar(32) NOT NULL,
  `CREATE_TIME` datetime DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_TIME` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`USER_ID`)
) ENGINE=InnoDB;
